apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiosk-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: kiosk-backend
  template:
    metadata:
      labels:
        app: kiosk-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
        imagePullPolicy: Always  
        ports:
        - containerPort: {{ .Values.backend.port }}
