apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiosk-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: kiosk-frontend
  template:
    metadata:
      labels:
        app: kiosk-frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.port }}